export const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS';
export const FETCH_CARS_FAILURE = 'FETCH_CARS_FAILURE';
export const FETCH_CARS_REQUEST = 'FETCH_CARS_REQUEST';
export const FETCH_CAR_ITEM_SUCCESS = 'FETCH_CAR_ITEM_SUCCESS';
export const FETCH_CAR_ITEM_FAILURE = 'FETCH_CAR_ITEM_FAILURE';
export const FETCH_CAR_ITEM_REQUEST = 'FETCH_CAR_ITEM_REQUEST';
