name: NodeJS CI
on:
  push:
    branches:
      - feature
  pull_request:
    branches:
      - feature
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Run Yarn 
      run: yarn
    - name: Run build
      run: yarn run build --if-present
    - name: Run tests
      run: yarn test